-- Hand-written: drizzle-kit doesn't model FTS5 virtual tables, so this migration
-- isn't generated by `drizzle-kit generate`. Kept in numeric sequence with the
-- generated migrations so `wrangler d1 migrations apply` runs it in order.
CREATE VIRTUAL TABLE areas_fts USING fts5(name, content='areas', content_rowid='id');
--> statement-breakpoint
CREATE VIRTUAL TABLE climbs_fts USING fts5(name, content='climbs', content_rowid='id');
