-- Hand-written: drizzle-kit doesn't model triggers, so this migration isn't
-- generated by `drizzle-kit generate`. Kept in numeric sequence with the
-- generated migrations so `wrangler d1 migrations apply` runs it in order,
-- and journaled by hand in meta/_journal.json (same as 0001_fts5_search).
--
-- Moves maintenance of the climbs.send_count/rating_sum/rating_count
-- aggregates out of app code and into the database. Before this, every
-- write path in db/mutations hand-rolled the same delta arithmetic
-- alongside its sends write; nothing structural stopped a new path from
-- forgetting it, and the counts back a real safety check (deleteClimb
-- refuses to delete a climb with send_count > 0).
--
-- Known gap: SQLite does not fire these DELETE triggers for rows removed by
-- ON DELETE CASCADE unless PRAGMA recursive_triggers is on, and D1 doesn't
-- expose that pragma. sends.user_id cascades from `user`, so if account
-- deletion is ever enabled (better-auth's deleteUser is opt-in and is
-- currently off), it must delete the user's sends explicitly first or the
-- counts will be left inflated. To repair drifted counts, re-run the
-- backfill UPDATE below — it recomputes all three columns from sends and is
-- safe to run at any time.

-- Backfill from a known-good state so the triggers take over from exact
-- values, rather than inheriting whatever app code last left behind.
UPDATE climbs SET
  send_count   = (SELECT COUNT(*) FROM sends WHERE sends.climb_id = climbs.id),
  rating_sum   = (SELECT COALESCE(SUM(rating), 0) FROM sends WHERE sends.climb_id = climbs.id AND rating IS NOT NULL),
  rating_count = (SELECT COUNT(*) FROM sends WHERE sends.climb_id = climbs.id AND rating IS NOT NULL);
--> statement-breakpoint
CREATE TRIGGER sends_aggregates_ai AFTER INSERT ON sends
BEGIN
  UPDATE climbs SET
    send_count   = send_count + 1,
    rating_sum   = rating_sum + COALESCE(new.rating, 0),
    rating_count = rating_count + (new.rating IS NOT NULL)
  WHERE id = new.climb_id;
END;
--> statement-breakpoint
CREATE TRIGGER sends_aggregates_ad AFTER DELETE ON sends
BEGIN
  UPDATE climbs SET
    send_count   = send_count - 1,
    rating_sum   = rating_sum - COALESCE(old.rating, 0),
    rating_count = rating_count - (old.rating IS NOT NULL)
  WHERE id = old.climb_id;
END;
--> statement-breakpoint
-- Full remove-then-add rather than a rating-only delta: this stays correct
-- if a send ever moves between climbs, and nets to zero on send_count for
-- the normal same-climb edit.
CREATE TRIGGER sends_aggregates_au AFTER UPDATE ON sends
BEGIN
  UPDATE climbs SET
    send_count   = send_count - 1,
    rating_sum   = rating_sum - COALESCE(old.rating, 0),
    rating_count = rating_count - (old.rating IS NOT NULL)
  WHERE id = old.climb_id;
  UPDATE climbs SET
    send_count   = send_count + 1,
    rating_sum   = rating_sum + COALESCE(new.rating, 0),
    rating_count = rating_count + (new.rating IS NOT NULL)
  WHERE id = new.climb_id;
END;
