/** Canonical production origin and site identity, shared by `metadataBase`,
 * per-page canonical URLs, the sitemap, and JSON-LD `url`/`item` values.
 *
 * Hard-coded rather than read from an env var: the custom domain is fixed in
 * wrangler.jsonc (`routes[].pattern`) and `BETTER_AUTH_URL`, and the build
 * has no runtime bindings to read from anyway. Change all three together. */
export const SITE_URL = "https://betabook.ca";

export const SITE_NAME = "Betabook";

/** One-line site description — the default `<meta name="description">` and the
 * fallback for pages that don't compose their own. */
export const SITE_DESCRIPTION =
  "Climbing logbook and crag database — routes, boulder problems, grades, and logged ascents.";

/** The sitewide Open Graph card, generated by `pnpm brand:generate` and
 * served at `/opengraph-image.png`. Named explicitly by `pageMetadata()`: a
 * route that returns its own `openGraph` object stops inheriting the root
 * file-convention image, so every content page has to re-point at it. */
export const OG_IMAGE = {
  url: "/opengraph-image.png",
  width: 1200,
  height: 630,
  alt: `${SITE_NAME} — climbing logbook and crag database`,
} as const;
